### ISSUE TITLE
Hi, This fix is solved if ToggleListItem has only one item.

### ISSUE THREAD

**Issue by adarshwebcastle** [BinaryBush/toggle_list#2]
Hi, This fix is solved if ToggleListItem has only one item.
If ToggleListItem have more than one item (example 2 items) then I need to click the first item 2 times to shrink it back,
another bug I found that if I try to shrink the second item then the first item also shrink back.

https://github.com/BinaryBush/toggle_list/assets/110030709/a591a6f8-2119-41bf-b181-1217612bbc4b

https://github.com/BinaryBush/toggle_list/assets/110030709/de709556-f48c-46df-b0d1-2893ba86c712

_Originally posted by @adarshwebcastle in https://github.com/BinaryBush/toggle_list/issues/1#issuecomment-1805683133_

**Comment by sarvarimark** [comment]
Thank you for your feedback!
Sorry for the slow response, I was trying to reproduce the bugs, but I didn't seem to find them.
I propose start with the first one: can you provide some clarification what do you mean by a ToggleListItem having two items? Also if you can share a code snippet, to help us reproduce the problem, it would be appreciated!

**Comment by sarvarimark** [comment]
The bug was caused by the fact that the submitter was using ToogleLists as content of ToogleListItems, which is not supported.
If you think this type of embedding should be a feature open a [feature request ticket](https://github.com/BinaryBush/toggle_list/issues/new?assignees=&labels=new-feature&template=2_feature_request.yaml) and let's discuss it!
